[package]
name = "dbmiru-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
dbmiru-core = { path = "../core" }
keyring = { workspace = true }
serde_json = { workspace = true }
